version: '3.8'
services:
   web:
       build: .
       command: python manage.py runserver 0.0.0.0:8000
       ports:
           - "8000:8000"
       volumes:
         - ./app:/usr/src/geoapi
       env_file:
         - ./.env
       depends_on:
         - db
   db:
     image: postgres:12.0-alpine
     ports:
       - "5433:5432"
     volumes:
       - postgres_data:/var/lib/postgresql/data/
     environment:
       - POSTGRES_USER=admin
       - POSTGRES_PASSWORD=admin
       - POSTGRES_DB=postgres_test
volumes:
  postgres_data: